### PR TITLE
Fixed icon shadows

### PR DESCRIPTION
**Pull request by lopatoj**

### CODE REVIEW

**Comment by stsdc** [comment]
Hi! Can you elaborate a bit on this change?

**Comment by stsdc** [comment]
@lopatoj ping

**Comment by stsdc** [comment]
@danirabbit can you tell the difference here?

**Comment by ryonakano** [comment]
> can you tell the difference here?

The bottom portion seems to get subtly brighten:

Before:
Screenshot from 2024-10-11 22-26-00

After:
Screenshot from 2024-10-11 22-26-05

**Comment by stsdc** [comment]
The question is: Should I merge this?
Is this in line with the overall icon style system?

**Comment by ryonakano** [comment]
> The question is: Should I merge this?
> Is this in line with the overall icon style system?

Yeah that's the next question, but I'm not sure because I'm not familiar with elementary HIG.
Any opinions from @elementary/ux?

**Review by wpkelso — APPROVED** [review]
You should be good to merge this

In the old version, the icon's drop shadow is sitting on top of the icon itself, while in the new one it's been pushed down the z-index to tuck under the icon. The shadow no longer being on top is whats causing the brightening :)

**Review by stsdc — APPROVED** [review]

**Pull request merged**
